### ISSUE TITLE
Split into title and description

### ISSUE THREAD

**Issue by dvogt23** [anjerodev/commitollama#6]
Great idea and prompts, trying to integrate something similiar to nvim and just realised that it might be better to adjust the prompt to have a short title and a longer description. Usually titles should not be longer than 72 characters. wdyt?

See: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by anjerodev** [comment]
Hi! thank for the suggestion! 😊 Now there is an option in the extension settings that allow to use commit description. 
Btw, you can set up a custom prompt in the extension settings as well.
