### ISSUE TITLE
Custom model cannot be set

### ISSUE THREAD

**Issue by mrAnomalyy** [anjerodev/commitollama#9]
Hey. I love your work, using this extension almost all the time!

One of the last changes was an update of default LLama3 Model name. It's been changed to llama3.1.
I had a reason not to pull new model and wanted to set a custom one – good ol' `llama3`. 

I faced the issue here, as you can see on screenshot, config parameters are set but extension tries to use default Llama3 model which is llama3.1 now.

<img width="988" alt="image" src="https://github.com/user-attachments/assets/2a15a489-ed9d-45f4-b677-dbc90f049b13">

**Comment by mrAnomalyy** [comment]
I almost sure the problem is on these lines https://github.com/anjerodev/commitollama/blob/e469b6f56fed4baa69c0bb50005ae6acc9df9e14/src/config.ts#L28-L31

here we try to use user input to find value in map, otherwise using default model. Next line tries to check if modelName (previous variable) is a "Custom". But there is no such model in our map. So if not to change this logic, maybe try to add `"custom": "Custom"` entry in the Models map?

I will put a PR for this if required, but I am not familiar with developing VS Code Extensions so it will take a time from me. If you could resolve this faster, that would be great.

Thank you!

**Comment by anjerodev** [comment]
Hello, I think the error is due to manually changing the extension setting in the VSCode settings JSON. Try setting "Custom" with an uppercase "C" instead of "custom". I believe that's the issue, because if you configure the custom model from VSCode settings > Extensions > commitollama, there is an option to select the model ("Custom"), and that problem shouldn't happen. Anyway, I will find a better way to set the model name so it is not case-sensitive.

**Comment by mrAnomalyy** [comment]
> Hello, I think the error is due to manually changing the extension setting in the VSCode settings JSON. Try setting "Custom" with an uppercase "C" instead of "custom". I believe that's the issue, because if you configure the custom model from VSCode settings > Extensions > commitollama, there is an option to select the model ("Custom"), and that problem shouldn't happen. Anyway, I will find a better way to set the model name so it is not case-sensitive.

Hey, good day to you, sir. Thank you for you being so operative on checking out issues here on this repo!

Yes, I already tried to put it as "Custom", this isn't helping, sadly.

Also just made an attempt to set those settings from UI, no success still :(

**Comment by anjerodev** [comment]
You were right, "Custom" was missing in the Models object, so the `modelName === "Custom"` assumption was never true. It should be working as expected now.
